routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AkunController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\DmvTipeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\MNavbarController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PesananController;
use App\Http\Controllers\PiutangController;
use App\Http\Controllers\CPesananController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DmvBahanController;
use App\Http\Controllers\DmvLebarController;
use App\Http\Controllers\TerminalController;
use App\Http\Controllers\JurnalUmumController;
use App\Http\Controllers\PembayaranController;
use App\Http\Controllers\MigrasiDataController;
use App\Http\Controllers\DmvFinishingController;
use App\Http\Controllers\PenerimaanKasController;
use App\Http\Controllers\PesananManualController;
use App\Http\Controllers\PengeluaranKasController;
use App\Http\Controllers\PesananCetakanController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\LaporanKeuanganController;
use App\Http\Controllers\MetodePembayaranController;
use App\Http\Controllers\PembayaranCetakanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// terminal
Route::group(['middleware' => ['auth', 'permission']], function () {
    Route::get('terminal', [TerminalController::class, 'index'])->name('terminal.index');
    Route::get('config-cache', [TerminalController::class, 'configCache'])->name('terminal.config-cache');
    Route::get('route-cache', [TerminalController::class, 'routeCache'])->name('terminal.route-cache');
    Route::get('route-list', [TerminalController::class, 'routeList'])->name('terminal.route-list');
    Route::get('route-clear', [TerminalController::class, 'routeClear'])->name('terminal.route-clear');
    Route::get('clear-cache', [TerminalController::class, 'clearCache'])->name('terminal.clear-cache');
    Route::get('clear-view', [TerminalController::class, 'clearView'])->name('terminal.clear-view');
    Route::get('clear-config', [TerminalController::class, 'clearConfig'])->name('terminal.clear-config');
});

Route::group(['middleware' => ['auth', 'permission']], function () {
    Route::get('rolepermission', [RolePermissionController::class, 'index'])->name('rolepermission.index');
    Route::get('rolepermission/create', [RolePermissionController::class, 'create'])->name('rolepermission.create');
    Route::post('roles/store', [RolePermissionController::class, 'storeRoles'])->name('roles.store');
    Route::post('roles/{roles?}', [RolePermissionController::class, 'delete'])->name('roles.delete');
    Route::get('rolepermission/settingrolepermission/{id?}', [RolePermissionController::class, 'settingrolepermission'])->name('rolepermission.settingrolepermission');
    Route::post('rolepermission/store/{id?}', [RolePermissionController::class, 'store'])->name('rolepermission.store');
    Route::get('rolepermission/listpengguna', [RolePermissionController::class, 'listpengguna'])->name('rolepermission.listpengguna');
    Route::get('menu', [MenuController::class, 'index'])->name('menu.index');
    Route::get('menu/create', [MenuController::class, 'create'])->name('menu.create');
    Route::get('menu/{menu}/edit', [MenuController::class, 'edit'])->name('menu.edit');
    Route::get('menu/{menu}', [MenuController::class, 'show'])->name('menu.show');
    Route::post('menu/{menu}/delete', [MenuController::class, 'destroy'])->name('menu.delete');
    Route::post('menu', [MenuController::class, 'store'])->name('menu.store');
    Route::post('menu/{menu}/update', [MenuController::class, 'update'])->name('menu.update');
    Route::get('list-menu-category', [MenuController::class, 'listMenuCategory'])->name('menu.list-menu-category.index');
    Route::get('menucategory/create', [MenuController::class, 'createCategoryMenu'])->name('menu.list-menu-category.create');
    Route::get('menucategory/{menucategory}/edit', [MenuController::class, 'editCategoryMenu'])->name('menu.list-menu-category.edit');
    Route::post('menu-category', [MenuController::class, 'storeCategoryMenu'])->name('menu.list-menu-category.store');
    Route::post('menu-category/{menucategory}/delete', [MenuController::class, 'destroyCategoryMenu'])->name('menu.list-menu-category.delete');
    Route::post('pembayaran/bayar', [PembayaranController::class, 'bayar'])->name('pembayaran.bayar');
});

Route::group(['middleware' => ['auth', 'permission'], 'prefix' => 'dmv'], function () {
    // dmv tipe
    Route::get('tipe', [DmvTipeController::class, 'index'])->name('dmv.tipe.index');
    Route::get('tipe/create', [DmvTipeController::class, 'create'])->name('dmv.tipe.create');
    Route::post('tipe', [DmvTipeController::class, 'store'])->name('dmv.tipe.store');
    Route::get('tipe/{tipe}/edit', [DmvTipeController::class, 'edit'])->name('dmv.tipe.edit');
    Route::post('tipe/{tipe}/update', [DmvTipeController::class, 'update'])->name('dmv.tipe.update');
    Route::post('tipe/{tipe}', [DmvTipeController::class, 'delete'])->name('dmv.tipe.delete');

    // dmv bahan
    Route::get('bahan', [DmvBahanController::class, 'index'])->name('dmv.bahan.index');
    Route::get('bahan/create', [DmvBahanController::class, 'create'])->name('dmv.bahan.create');
    Route::post('bahan', [DmvBahanController::class, 'store'])->name('dmv.bahan.store');
    Route::get('bahan/{bahan}/edit', [DmvBahanController::class, 'edit'])->name('dmv.bahan.edit');
    Route::get('bahan/{bahan}/show', [DmvBahanController::class, 'show'])->name('dmv.bahan.show');
    Route::post('bahan/{bahan}/update', [DmvBahanController::class, 'update'])->name('dmv.bahan.update');
    Route::post('bahan/{bahan}', [DmvBahanController::class, 'destroy'])->name('dmv.bahan.delete');

    // dmv lebar
    Route::get('lebar', [DmvLebarController::class, 'index'])->name('dmv.lebar');

    // dmv finishing
    Route::get('finishing', [DmvFinishingController::class, 'index'])->name('dmv.finishing');
    Route::get('finishing/create', [DmvFinishingController::class, 'create'])->name('dmv.finishing.create');
    Route::post('finishing', [DmvFinishingController::class, 'store'])->name('dmv.finishing.store');
    Route::get('finishing/{finishing}/edit', [DmvFinishingController::class, 'edit'])->name('dmv.finishing.edit');

    // dmv  pesanan
    Route::get('pesanan', [PesananController::class, 'index'])->name('pesanan.index');
    Route::get('pesanan/create', [PesananController::class, 'create'])->name('pesanan.create');
    Route::post('pesanan/store', [PesananController::class, 'store'])->name('pesanan.store');
    Route::post('pesanan/{pesanan}/update', [PesananController::class, 'update'])->name('pesanan.update');
    Route::get('pesanan/{pesanan}/show', [PesananController::class, 'show'])->name('pesanan.show');
    Route::get('pesanan/{pesanan}/edit', [PesananController::class, 'edit'])->name('pesanan.edit');
    // Route::get('/pesanan/create-cetakan', [PesananController::class, 'createCetakan'])->name('pesanan.create-cetakan');

    // dmv cetakan
    Route::resource('pesanan-cetakan', PesananCetakanController::class);

    // dmv pembayaran
    Route::get('pembayaran', [PembayaranController::class, 'index'])->name('pembayaran.index');
    Route::get('pembayaran/{customer}', [PembayaranController::class, 'pembayaran'])->name('pembayaran.detail');
    Route::get('load-table-customer', [PembayaranController::class, 'tableCustomer'])->name('pembayaran.load-table-customer');
    Route::get('pembayaran/get-customer-html', [PembayaranController::class, 'getCustomersHtml'])->name('pembayaran.get-customer-html');
    Route::post('clear-keranjang', [PembayaranController::class, 'clearKeranjang'])->name('pembayaran.clear-keranjang');
    Route::post('invoice', [InvoiceController::class, 'store'])->name('invoice.store');
    Route::delete('pembayaran/{keranjang}', [PembayaranController::class, 'hapusKeranjang'])->name('keranjang.destroy');
    Route::get('pembayaran/struk/{invoice}', [PembayaranController::class, 'struk'])->name('pembayaran.struk');
    Route::get('spk/{invoice}', [PembayaranController::class, 'spk'])->name('spk');
    Route::post('pembayaran/angsuran', [PembayaranController::class, 'bayarAngsuranInvoice'])->name('pembayaran.angsuran');

    // migrasi data
    Route::get('migrasi', [MigrasiDataController::class, 'index'])->name('migrasi.index');

    // Navbar
    Route::resource('navbar', MNavbarController::class);
    Route::post('isactive', [MNavbarController::class, 'isActive'])->name('isactive');
});

Route::group(['middleware' => ['auth', 'permission']], function () {
    // konfigurasi pesanan
    Route::get('/cpesanan', [CPesananController::class, 'index'])->name('cpesanan.index');
    Route::post('/cpesanan/drag', [CPesananController::class, 'drag'])->name('cpesanan.drag');
    Route::post('/cpesanan/plate', [CPesananController::class, 'plate'])->name('cpesanan.plate');

    // akun
    Route::get('/akun', [AkunController::class, 'index'])->name('akun.index');
    Route::post('/akun', [AkunController::class, 'store'])->name('akun.store');
    Route::post('/mapping_saldo_normal', [AkunController::class, 'mappingSaldoNormal'])->name('akun.mapping_saldo_normal');
    Route::get('subklasifikasi', [AkunController::class, 'subklasifikasi'])->name('akun.subklasifikasi');

app/Http/Controllers/PesananCetakanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customers;
use App\Models\Outstanding;
use Illuminate\Http\Request;
use App\Models\PesananCetakan;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\PesananCetakanRequest;
use App\Models\Transaksi;

class PesananCetakanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $payload['start_date'] = $request->input('start_date', startDate());
        $payload['end_date'] = $request->input('end_date', endDate());
        $payload['show'] = $request->input('show', 20);
        $payload['keyword'] = $request->input('search', '');
        $data = PesananCetakan::getAllCetakan($payload);
        return view('pesanancetakan.index', compact('data', 'payload'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Request $request)
    {
        if ($request->ajax() && $request->autocomplete) {
            $query = $request->input('search');
            $results = Customers::select('id', 'nama', 'member')->where('nama', 'like', '%' . $query . '%')->limit(10)->get();
            $response = array();
            foreach ($results as $value) {
                $response[] = [
                    'value' => $value->id,
                    'label' => strtoupper($value->nama),
                ];
            }
            return response()->json(['data' => $response]);
        }
        $url = route('pesanan-cetakan.store');
        return view('dmv.pesanan.create', compact('url'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(PesananCetakanRequest $request)
    {
        $response = '';
        try {
            DB::beginTransaction();
            $pesanan = PesananCetakan::create($request->all());
            $this->createJurnalPesanan($pesanan);
            DB::commit();
            $response = [
                'success' => true,
                'message' => 'Pesanan Berhasil Disimpan'
            ];
        } catch (\Exception $e) {
            DB::rollBack();
            logError($e);
            $response = [
                'success' => false,
                'message' => $e->getMessage()
            ];
        }
        return $response;
    }

    /**
     * Display the specified resource.
     */
    public function show(PesananCetakan $pesanan_cetakan)
    {
        $pesanan_cetakan->load('customer');
        return view('pesanancetakan.show', compact('pesanan_cetakan'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(PesananCetakan $pesanan_cetakan)
    {
        $pesanan_cetakan->load('customer');
        $pesanan = $pesanan_cetakan;
        $url = route('pesanan-cetakan.update', $pesanan->id);
        $update = true;
        return view('dmv.pesanan.create', compact('pesanan', 'url', 'update'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(PesananCetakanRequest $request, PesananCetakan $pesanan_cetakan)
    {
        try {
            DB::beginTransaction();
            $outstanding = Outstanding::where('customer_id', $request->customer_id)->first();
            $outstanding->nominal -= $pesanan_cetakan->total_harga;
            $outstanding->save();
            $pesanan_cetakan->update($request->all());
            $outstanding->nominal += $request->total_harga;
            $outstanding->save();

            $jurnal = Transaksi::where('no_pesanan', $pesanan_cetakan->no_pesanan)->with('jurnal')->first();
            $jurnal->nominal = $request->total_harga;
            $jurnal->save();
            $jurnal->jurnal[0]->update(['debet' => $jurnal->nominal]);
            $jurnal->jurnal[1]->update(['kredit' => $jurnal->nominal]);
            DB::commit();
            $response = [
                'success' => true,
                'message' => 'Data Berhasil Diubah'
            ];
        } catch (\Exception $e) {
            DB::rollBack();
            logError($e);
            $response = [
                'success' => false,
                'message' => $e->getMessage()
            ];
        }
        return $response;
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/pesanancetakan/index.blade.php
@extends('layouts.main')
@section('konten')
    <x-table :data="$data" :columns="config('table_config.pesanan_cetakan')" :tr="'show', 'edit'">
        <x-slot name="header">
            <x-header-table :title="'List Pesanan Cetakan'">
                <div class="space-x-2">
                    <a href="{{ route('pesanan-cetakan.create') }}" class="btn btn-md rn btn-indigo">
                        Buat Pesanan Cetakan
                    </a>
                </div>
            </x-header-table>
        </x-slot>
        <x-slot name="customfilter">
            <form action="{{ Request::url() }}" method="GET" class="grid grid-cols-3 mb-5">
                <div date-rangepicker datepicker-format="yyyy-mm-dd" class="flex items-center gap-x-2">
                    <div class="relative">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <x-icon-calender />
                        </div>
                        <input name="start_date" type="text" class="date-filter" placeholder="start"
                            value="{{ $payload['start_date'] ?? '' }}" autocomplete="off">
                    </div>
                    <span class="mx-2 text-gray-500">to</span>
                    <div class="relative">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <x-icon-calender />
                        </div>
                        <input name="end_date" type="text" class="date-filter" placeholder="end"
                            value="{{ $payload['end_date'] ?? '' }}" autocomplete="off">
                    </div>
                    <button class="btn btn-indigo">Filter</button>
                </div>
            </form>
        </x-slot>
        <x-slot name="filter">
            <x-show-data :show="$payload['show']" />
            <x-search :keyword="$payload['keyword']" />
        </x-slot>
    </x-table>
@endsection
@push('scripts')
    <script type="text/javascript">
        function _show(id, el) {
            window.location.href = "{{ route('pesanan-cetakan.show', ':id') }}".replace(':id', id);
        }
    </script>
@endpush

resources/views/pesanancetakan/show.blade.php
@extends('layouts.main')
@section('konten')
    <div class="contianer max-w-sm bg-white rounded-md shadow-md">
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li class="font-bold flex items-center space-x-3"> <svg xmlns="http://www.w3.org/2000/svg" width="1.2em"
                    height="1.2em" viewBox="0 0 48 48">
                    <path fill="#bbdefb" d="M7 4h34v40H7z" />
                    <path fill="#2196f3"
                        d="M13 26h4v4h-4zm0-8h4v4h-4zm0 16h4v4h-4zm0-24h4v4h-4zm8 16h14v4H21zm0-8h14v4H21zm0 16h14v4H21zm0-24h14v4H21z" />
                </svg> Detail Pesanan Cetakan</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Tanggal</li>
            <li>{{ $pesanan_cetakan->tanggal }}</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Customer</li>
            <li>{{ $pesanan_cetakan->customer->nama }}</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Nama Cetakan</li>
            <li>{{ $pesanan_cetakan->nama_cetakan }}</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Jumlah Cetakan</li>
            <li>{{ $pesanan_cetakan->jumlah_cetakan }}</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Jumlah Drag</li>
            <li>{{ $pesanan_cetakan->jumlah_drag }}</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Jenis Cetak</li>
            <li>{{ $pesanan_cetakan->jenis_cetak }}</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Jumlah Plate</li>
            <li>{{ $pesanan_cetakan->jumlah_plate }}</li>
        </ul>
        <ul class="flex justify-between items-center border-b p-3 text-gray-700">
            <li>Total Harga</li>
            <li>{{ rupiah($pesanan_cetakan->total_harga) }}</li>
        </ul>
        <ul class="flex justify-end space-x-1.5 items-center border-b p-3 text-gray-700">
            {{-- <li><button class="btn btn-md btn-indigo">Print</button></li> --}}
            <li><a class="btn btn-md btn-emerald" href="{{ route('pesanan-cetakan.edit', $pesanan_cetakan->id) }}">Edit</a>
            </li>
            <li><a class="btn btn-md btn-indigo" href="{{ route('pesanan-cetakan.index') }}">Kembali</a></li>
            {{-- <li><a class="btn btn-md btn-rose">Hapus</a></li> --}}
        </ul </div>
    @endsection